### ISSUE TITLE
Lesson Contribution: Suggested Updates

### ISSUE THREAD

**Issue by Talishask** [carpentries-incubator/camera-traps#3]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

It appears that what is on the web is a sort of place holder.

First, an easy fix:

* There is an error message: Invalid value for variable carpentry defined in _config.yml. Current value: Data Carpentry allowed values: ("swc", "dc", "lc", "cp", "incubator", "lab")
* This just needs to have "Data Carpentry" changed to "dc."

Second, this is a topic I know something about, so in the way of brainstorming different episodes, we might consider:

* Image file formats
* Image exif metadata
* Storing, retrieving, and managing image data
* Loading, converting, displaying, saving images in python
* Image processing in Python (for example using PIL/Pillow, numpy, scikit-image, and OpenCV)
* Tools and techniques for labeling and annotating images
* Computer vision methods (intro)
* Preparing images for machine learning/deep learning (at some point, this may get more into software carpentry if we get into CV, DL,…)

**Comment by evebohnett** [comment]
Thanks I'm updating the site now.
